### ISSUE TITLE
Failed build

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/app.drey.Blurble#1]
It looks like that the [latest commit](https://github.com/flathub/app.drey.Blurble/commit/c17e88fac7cbafd954260a6bfb69f700cae7a76f) from September 27, 2022 has failed build and so the actual latest build on Flathub is from July 29, 2022.

**Comment by hfiguiere** [comment]
```
• file-invalid          : <screenshot> failed to load [https://gitlab.gnome.org/World/Blurble/-/raw/main/data/screenshots/screenshot-2.png]
```

I guess when I say to no references branches like that, I'm right. The screenshot is gone.

**Comment by AsciiWolf** [comment]
That was a quick fix! Thanks, Hubert. :-)
